CREATE DATABASE G7_DATABASE;
GO

USE G7_DATABASE;
GO

CREATE TABLE ROLES(
	ID_ROLE BIGINT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NAME_ROLE VARCHAR(100) NOT NULL,
	DESC_ROLE VARCHAR(200) NOT NULL,
	ACTIVE INT NOT NULL
);

GO

CREATE TABLE Users(
	USU_ID VARCHAR(12) PRIMARY KEY NOT NULL, 
	FIRST_NAME VARCHAR(60) NOT NULL,
	LAST_NAME  VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL, 
	PASSWD VARCHAR(100) NOT NULL,
	TEMP_PASSWD VARCHAR(100) NULL,
	ACTIVE INT NOT NULL,
	ID_ROLE BIGINT NOT NULL,
	FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID_ROLE)

);

GO

CREATE TABLE STATE_TICKET(
	ID_STATE BIGINT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NAME_STATE VARCHAR(100) NOT NULL,
	DESC_STATE VARCHAR(200) NOT NULL,
	ACTIVE INT NOT NULL
);

GO

CREATE TABLE TICKET(
	ID_TICKET BIGINT PRIMARY KEY NOT NULL IDENTITY(1,1),
	TITLE VARCHAR(100) NOT NULL, 
	DESC_TICKET VARCHAR(200) NOT NULL,
	ID_STATE BIGINT NOT NULL,
	ACTIVE INT NOT NULL,
	USU_OPEN VARCHAR(12) NOT NULL,
	USU_CHECK VARCHAR(12) NULL,
	USU_APROVE VARCHAR(12) NULL,
	USU_ARCHIVE VARCHAR(12) NULL,
	USU_DELETE VARCHAR(12) NULL,
	USU_COMPLETE VARCHAR(12) NULL,
	FOREIGN KEY (ID_STATE) REFERENCES STATE_TICKET(ID_STATE),
	FOREIGN KEY (USU_OPEN) REFERENCES USERS(USU_ID),
	FOREIGN KEY (USU_CHECK) REFERENCES USERS(USU_ID),
	FOREIGN KEY (USU_APROVE) REFERENCES USERS(USU_ID),
	FOREIGN KEY (USU_ARCHIVE) REFERENCES USERS(USU_ID),
	FOREIGN KEY (USU_DELETE) REFERENCES USERS(USU_ID),
	FOREIGN KEY (USU_COMPLETE) REFERENCES USERS(USU_ID)
);

GO