//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class G7_DATABASEEntities : DbContext
    {
        public G7_DATABASEEntities()
            : base("name=G7_DATABASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<STATE_TICKET> STATE_TICKET { get; set; }
        public virtual DbSet<TICKET> TICKETs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
