//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public long ID_TICKET { get; set; }
        public string TITLE { get; set; }
        public string DESC_TICKET { get; set; }
        public long ID_STATE { get; set; }
        public int ACTIVE { get; set; }
        public string USU_OPEN { get; set; }
        public string USU_CHECK { get; set; }
        public string USU_APROVE { get; set; }
        public string USU_ARCHIVE { get; set; }
        public string USU_DELETE { get; set; }
        public string USU_COMPLETE { get; set; }
    
        public virtual STATE_TICKET STATE_TICKET { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
    }
}
